"""
    Settings file
"""

# MySQL informations
DB_NAME = 'ocpizza'
DB_USER = 'ocpizza'
DB_HOST = 'localhost'
DB_PWD = 'ocpizza'

# Language code for data
LANG_CODE = 'fr_FR'

# File for generating the SQL structure
SQL_STRUCTURE = 'OCPizza-structure.sql'

# Instance count for each object
CUSTOMERS_COUNT = 67
RESTAURANTS_COUNT = 4
EMPLOYEES_COUNT_MIN = 3
EMPLOYEES_COUNT_MAX = 5
INGREDIENTS_COUNT = 15
SIZES_COUNT = 3
CATEGORIES_COUNT = 15
PIZZA_COUNT = 20
STATUS_COUNT = 4
STATUS_HISTORY_MIN = 1
STATUS_HISTORY_MAX = 3
PAYMENTS_TYPE_COUNT = 2
PAYMENTS_STATUS_COUNT = 2
ORDERS_COUNT_MIN = 0
ORDERS_COUNT_MAX = 4
ORDERS_LINES_COUNT_MIN = 1
ORDERS_LINES_COUNT_MAX = 6
